Module 4

In [9]:
import numpy as np
arr = np.array([0,1,2,3,5,8,13])
result = filter(lambda a:a%2==0,arr)
print(list(result))

[0, 2, 8]


Concatination

In [24]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(7,13).reshape(2,3)
print("B:",b)

c=np.concatenate((a,b))
print("Concatinated:",c)

A: [[0 1 2]
 [3 4 5]]
B: [[ 7  8  9]
 [10 11 12]]
Concatinated: [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [29]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(7,16).reshape(3,3)
print("B:",b)

c=np.arange(20,32).reshape(4,3)
print("C:",c)

d=np.concatenate((a,b,c))
print("Concatenated:\n",d)

A: [[0 1 2]
 [3 4 5]]
B: [[ 7  8  9]
 [10 11 12]
 [13 14 15]]
C: [[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]
Concatinated:
 [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


In [83]:
a=np.arange(6).reshape(2,3)
b=np.arange(7,16).reshape(3,3)

mat=np.concatenate((a,b),axis=0)
print(mat)


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Stack


In [86]:
a=np.arange(6).reshape(2,3)
b=np.arange(10,16).reshape(2,3)
stack_mat = np.stack((a,b),axis=2)
print(stack_mat)



[[[ 0 10]
  [ 1 11]
  [ 2 12]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]]


Vstack

In [7]:
a=np.arange(6).reshape(2,3)
b=np.arange(10,16).reshape(2,3)
stack_mat=np.vstack((a,b),axis=1)
print(stack_mat)

NameError: name 'np' is not defined

In [12]:
#import numpy as np
mat=np.dstack((a,b),axis=1)
print(mat[0,0,1])
print(mat)

NameError: name 'a' is not defined